# -*- coding: utf-8 -*-
"""BE23B007 - BT 5240 - Assignment 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ihFFgdfUIxNIJbcgwchzu9ZXFA0Ptfy

BT5240 - Computational Systems Biology <br> <hr>
Assignment 2
---

Question 1:
---
Download the yeast protein–protein interaction network and load it into NetworkX. <br>
a) Report basic network statistics, including the number of nodes and edges, density, and diameter.<br><hr>
b) Compute Degree, Betweenness, and Closeness centrality and briefl y explain what each measure represents in the context of a protein–protein interaction network. <br><hr>
c) Identify the top 5% of nodes for each centrality measure and treat them as putative essential proteins. <br><hr>
d) Independently remove each of these node sets from the network and measure the size of the largest connected component. <br><hr>
e) To assess statistical signifi cance, simulate 100 iterations of random removal of 5% of nodes and compare the results with the centrality-based removals by computing Z-scores. Comment on the suitability of using Z-scores based on the distribution obtained from random removals, and conclude which centrality measure best supports the centrality–lethality hypothesis for this network. <br><hr>
f) Find at least three nodes with high Betweenness Centrality but relatively low Degree. Based on PPI network topology, explain why these specific "bottleneck" proteins might be biologically essential even if they don't have many neighbours. <br><hr>
g) Using a database like SGD (Saccharomyces Genome Database), look up the top 2 nodes from your Closeness Centrality list. Do their known biological functions justify their central position, or could their high centrality be an artefact of study bias? <br> <hr>
"""

#import the required packages
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy
import copy
import random
import seaborn

from scipy.io import mmread #import mmread to read the contents of the .mtx file

adj_mat = mmread("bio-yeast.mtx") # import the .mtx file
G = nx.from_scipy_sparse_array(adj_mat) # construct the required graph using the relevant nx function

G = nx.relabel_nodes(G, lambda x: (x+1)) # relabel nodes so that the first node has the index 1

if nx.is_directed(G): # check if the graph is directed or undirected
  print('The given graph is directed.')
else:
  print('The given graph is undirected.')

"""a) Report basic network statistics, including the number of nodes and edges, density, and diameter.<br><hr>"""

# report the required network parameters
print('The number of nodes in the yeast PPIN is', G.number_of_nodes(), 'node(s).')
print('The number of edges in the yeast PPIN is', G.number_of_edges(), 'edge(s).')
print('The density of the yeast PPIN is {}.'.format(nx.density(G)))
print('The diameter of the yeast PPIN is {}.'.format(nx.diameter(G)))

"""b) Compute Degree, Betweenness, and Closeness centrality and briefl y explain what each measure represents in the context of a protein–protein interaction network. <br><hr>"""

# report the required centrality measures
print('The average degree centrality of the yeast PPIN is {}.'.format(sum(nx.degree_centrality(G).values()) / G.number_of_nodes()))
print('The average betweenness centrality of the yeast PPIN is {}.'.format(sum(nx.betweenness_centrality(G).values()) / G.number_of_nodes()))
print('The average closeness centrality of the yeast PPIN is {}.'.format(sum(nx.closeness_centrality(G).values()) / G.number_of_nodes()))

"""c) Identify the top 5% of nodes for each centrality measure and treat them as putative essential proteins. <br><hr>
d) Independently remove each of these node sets from the network and measure the size of the largest connected component. <br><hr>
"""

# the number representing top 5% of the total number of nodes is stored in 'fraction'
fraction = G.number_of_nodes() // 20
print('5% of the total number of nodes in the given yeast PPIN =',fraction, 'node(s).')

"""1. We calculate the specific centrality measure for all nodes. <br>
2. Then, sort the nodes according to the centrality measure, and pick the top 5% ones. <br>
3. Remove this set of nodes, and report the size of the largest connected component. <br>
<hr>
"""

# for degree centrality
G1 = copy.deepcopy(G) # use the copy.deepcopy() function to create a deepcopy of the graph G
print('The number of nodes in the original graph is {} node(s).'.format(G1.number_of_nodes()))
degree_dict = nx.degree_centrality(G1)
ordered_degree_dict = sorted(degree_dict.items(), key=lambda node: node[1], reverse = True)
degree_top_nodes = ordered_degree_dict[0:fraction]
node_set_degree = []
for i in degree_top_nodes:
  node_set_degree.append(i[0])
print('The top 5% nodes with the highest degree centrality are\n{}.'.format(node_set_degree))
G1.remove_nodes_from(node_set_degree)
print('The number of nodes upon removing top 5% of the nodes with the highest degree centrality is {} node(s).'.format(G1.number_of_nodes()))
largest_cc_degree = max(nx.connected_components(G1), key=len)
print('The size of the largest component on removing top 5% of the nodes in the original graph \n(without recomputing degree centrality for every removal) is {} nodes.'.format(len(largest_cc_degree)))

# for betweenness centrality

G2 = copy.deepcopy(G) # use the copy.deepcopy() function to create a deepcopy of the graph G
print('The number of nodes in the original graph is {} node(s).'.format(G.number_of_nodes()))
betweenness_dict = nx.betweenness_centrality(G2)
ordered_betweenness_dict = sorted(betweenness_dict.items(), key = lambda node: node[1], reverse = True)
betweenness_top_nodes = ordered_betweenness_dict[0:fraction]
node_set_betn = []
for i in betweenness_top_nodes:
  node_set_betn.append(i[0])
G2.remove_nodes_from(node_set_betn)
print('The top 5% nodes with the highest betweenness centrality are\n{}.'.format(node_set_betn))
print('The number of nodes upon removing top 5% of the nodes with the highest betweenness centrality is {} node(s).'.format(G2.number_of_nodes()))
largest_cc_betweenness = max(nx.connected_components(G2), key=len)
print('The size of the largest component on removing top 5% of the nodes in the original graph \n(without recomputing betweenness centrality for every removal) is {} nodes.'.format(len(largest_cc_betweenness)))

# for closeness centrality
G3 = copy.deepcopy(G) # use the copy.deepcopy() function to create a deepcopy of the graph G
print('The number of nodes in the original graph is {} node(s).'.format(G3.number_of_nodes()))
closeness_dict = nx.closeness_centrality(G3)
ordered_closeness_dict = sorted(closeness_dict.items(), key = lambda node: node[1], reverse = True)
closeness_top_nodes = ordered_closeness_dict[0:fraction]
node_set_close = []
for i in closeness_top_nodes:
  node_set_close.append(i[0])
G3.remove_nodes_from(node_set_close)
print('The top 5% nodes with the highest betweenness centrality are\n{}.'.format(node_set_close))
print('The number of nodes upon removing top 5% of the nodes with the highest closeness centrality is {} node(s).'.format(G3.number_of_nodes()))
largest_cc_closeness = max(nx.connected_components(G3), key=len)
print('The size of the largest component on removing top 5% of the nodes in the original graph \n(without recomputing closeness centrality for every removal) is {} nodes.'.format(len(largest_cc_closeness)))

"""e) To assess statistical signifi cance, simulate 100 iterations of random removal of 5% of nodes and compare the results with the centrality-based removals by computing Z-scores. Comment on the suitability of using Z-scores based on the distribution obtained from random removals, and conclude which centrality measure best supports the centrality–lethality hypothesis for this network. <br><hr>"""

distribution_list = []
for i in range(0, 100): # perform 100 iterations of uniformly random sampling and removal of top 5% nodes
  rand_node_list = random.sample(range(0, G.number_of_nodes()), fraction)
  G4 = copy.deepcopy(G)
  G4.remove_nodes_from(rand_node_list)
  largest_cc = max(nx.connected_components(G4), key=len)
  distribution_list.append(len(largest_cc))

distribution = np.array(distribution_list) # store the distribution of the sizes of the largest connected component

# plot the histogram for this distribution

plt.hist(distribution, bins = 150)
plt.xlabel('Size of the largest connected component')
plt.ylabel('Frequency')
plt.title('Frequency distribution of the size of the largest connected component on random removal')
plt.show()

# calculate sample mean and standard deviation

mean = np.mean(distribution)
print('The mean of the distribution obtained from 100 iterations of random removal of 5% of nodes is {}.'.format(mean))
std = np.std(distribution)
print('The standard deviation of the distribution obtained from 100 iterations of random removal of 5% of nodes is {} .\n'.format(std))

# calculate the required Z-scores and p-values

z_degree = abs((len(largest_cc_degree) - mean) / std)
p_value_degree = scipy.stats.norm.sf(abs(z_degree))*2

z_betweenness = abs((len(largest_cc_betweenness) - mean) / std)
p_value_betweenness = scipy.stats.norm.sf(abs(z_betweenness))*2

z_closeness = abs((len(largest_cc_closeness) - mean) / std)
p_value_closeness = scipy.stats.norm.sf(abs(z_closeness))*2

print('The Z-score for the degree centrality-based removal is {} and the associated p value is {}.'.format(z_degree, p_value_degree))
print('The Z-score for the betweenness centrality-based removal is {} and the associated p value is {}.'.format(z_betweenness, p_value_betweenness))
print('The Z-score for the closeness centrality-based removal is {} and the associated p value is {}.'.format(z_closeness, p_value_closeness))

print('The nodes with relatively high Betweenness Centrality but relatively low Degree Centrality are given as follows:\n')
for i in range(0, 50):
  node = betweenness_top_nodes[i][0]
  if degree_dict[node] < 0.1 * ordered_degree_dict[0][1]:
    print('Node {} with degree centrality {} and betweenness centrality {}.'.format(node, degree_dict[node], betweenness_dict[node]))
print('\nThe node {} has the maximum degree centrality {} and the node {} has the maximum betweenness centrality {} in the graph.'.format(ordered_degree_dict[0][0], ordered_degree_dict[0][1], ordered_betweenness_dict[0][0], ordered_betweenness_dict[0][1]))

"""f) Find at least three nodes with high Betweenness Centrality but relatively low Degree. Based on PPI network topology, explain why these specific "bottleneck" proteins might be biologically essential even if they don't have many neighbours. <br><hr>"""

# the arbitrary definition of 'high betweenness centrality but low degree centrality is given in the report
print('The top 2 nodes with the highes closeness centrality are given as follows:\n')
for i in range(0, 2):
    print('Node {} with closeness centrality {}.'.format(ordered_closeness_dict[i][0], ordered_closeness_dict[i][1]))

"""g) Using a database like SGD (Saccharomyces Genome Database), look up the top 2 nodes from your Closeness Centrality list. Do their known biological functions justify their central position, or could their high centrality be an artefact of study bias? <br> <hr>"""

Y = nx.read_edgelist("yeast.edgelist")
closeness_dict_Y = nx.closeness_centrality(Y)
ordered_closeness_dict_Y = sorted(closeness_dict_Y.items(), key = lambda node: node[1], reverse = True)
print('The top 2 nodes with the highes closeness centrality are given as follows:\n')
for i in range(0, 2):
    print('Node {} with closeness centrality {}.'.format(ordered_closeness_dict_Y[i][0], ordered_closeness_dict_Y[i][1]))

"""Question 2:
---
Using the Zachary Karate Club Network, which represents friendships among members of a karate club that eventually split into factions, compare the Girvan–Newman algorithm and the greedy modularity maximization algorithm. <hr>
1. Use NetworkX to apply greedy modularity maximization while restricting the maximum number of communities to 2, 3, and 4. <br> For each case, report the modularity value and community sizes. Examine how modularity changes with increasing number of communities, identify the partition with maximum modularity, and determine whether it recovers the known real-life split. <hr>
2. Use NetworkX to apply the Girvan–Newman algorithm and analyze the fi rst fi ve successive partitions produced by the Girvan–Newman algorithm. <br> For each partition, record the number of communities, community sizes, and modularity. Identify the partition with maximum modularity, check whether it aligns with the real-life split, and describe how modularity changes as edges are progressively removed. <hr>
3. Compare the two algorithms in terms of maximum modularity achieved, computational complexity, and their ability to detect the real-life community structure. <hr>
4. In the Girvan-Newman algorithm, multiple edges often have the exact same maximum edge-betweenness. Explain how the NetworkX function handles these ties. <hr>
5. The greedy modularity maximization algorithm is known to suff er from a "resolution limit." <br> Did you observe any instances where the algorithm merged small, distinct functional groups into a single community to artificially boost the modularity score?<hr>
Note: Load the network using NetworkX. Real split can be obtained from node attributes. <hr>
"""



K = nx.karate_club_graph() # import Zachary's Karate Club graph

def composition(c): # define a function to report the composition of the partitions in a community structure of the Karate Club graph
  for partitions in c:
    mr_hi_count = 0
    officer_count = 0
    for p in partitions:
      if K.nodes()[p]['club'] == 'Mr. Hi':
        mr_hi_count = mr_hi_count + 1
      else:
        officer_count = officer_count + 1

    print('The composition of community {} is \n{} Mr. Hi and {} Officer.'.format([node for node in partitions], mr_hi_count, officer_count))

attributes = nx.get_node_attributes(K, 'club') # obtain attributes of all nodes
communities_real = [[0]] # initialise a partition by including node 0
# obtain the real-life split of the Karate Club graph
for i in range(1, K.number_of_nodes()):
  check = False
  for j in range(len(communities_real)):
    if attributes[i] == attributes[communities_real[j][0]]: # check if the attribute of a node matches that of any partition
      communities_real[j].append(i)
      check = True
  if check == False: # if the attribute of a node does not match with that of any partition, create a new partition
    communities_real.append([i])
print("The real split of the communities in the Zachary's Karate Club graph is given as follows:\n{}.\n".format(communities_real))
composition(communities_real)

# calculate modularity, number of communities in the Karate Club graph
modularity_real = nx.community.modularity(K, communities_real)
print("The modularity of Zachary's Karate Club graph is {}.".format(modularity_real))
no_of_comm_real = len(communities_real)
print("The number of communities in Zachary's Karate Club graph is {}.".format(no_of_comm_real))

"""1. Use NetworkX to apply greedy modularity maximization while restricting the maximum number of communities to 2, 3, and 4. <br> For each case, report the modularity value and community sizes. Examine how modularity changes with increasing number of communities, identify the partition with maximum modularity, and determine whether it recovers the known real-life split. <hr>"""

control_modularity_mod = 0
for i in range (2, 5):
  c = nx.community.greedy_modularity_communities(K, best_n = i) # greedy modularity optimization algorithm
  modularity = nx.community.modularity(K, communities = c)
  # determine community structure with the maximum modularity
  if modularity > control_modularity_mod:
    max_modularity_partitions_mod = c
    control_modularity_mod = modularity
  print('The maximum number of communities allowed is {} communities.'.format(i)) # constraint maximum number of communities allowed
  print('The modularity of the graph in this case is {}.'.format(modularity)) # report modularity of the community structure
  print('The communities are given as follows:')
  for j in range(len(c)):
    print('The size of community {} is {}.'.format(j+1, len(c[j]))) # report size of a community
    c_nodes = [nodes for nodes in c[j]]
    print('The nodes in commmunity {} are {}.'.format(j+1, c_nodes)) # report the nodes in a community
  print('\n')
  composition(c) # use the function composition to report composition of all partitions in a community structure
  print('-'*100)

# report community structure with the maximum modularity
print('The partition with the maximum modularity is {}.'.format(control_modularity_mod))
print('The number of communities in this case is {} communities.'.format(len(max_modularity_partitions_mod)))
print('The communities are given as follows:')
for j in range(len(max_modularity_partitions_mod)):
  print('The size of community {} is {}.'.format(j+1, len(max_modularity_partitions_mod[j])))
  c_nodes = [nodes for nodes in max_modularity_partitions_mod[j]]
  print('The nodes in commmunity {} are {}.'.format(j+1, c_nodes))
print('\n')
composition(max_modularity_partitions_mod) # use the function composition to report composition of all partitions in a community structure
print('-'*100)

"""We compare the community structure with the maximum modularity with Zachary's Karate Club graph on the basis of number of communities and modularity. <hr>"""

if len(max_modularity_partitions_mod) != no_of_comm_real:
  print("The number of communities in the original Zachary's Karate Club graph \nand in the partition with maximum modularity based on the greedy modularity optimization algorithm are unequal.")
else:
  print("The number of communities in the original Zachary's Karate Club graph \nand in the partition with maximum modularity based on the greedy modularity optimization algorithm are equal.")

if control_modularity_mod != modularity_real:
  print("The modularity of the original Zachary's Karate Club graph \nand that of the partition with maximum modularity based on the greedy modularity optimization algorithm are unequal.")
else:
  print("The modularity of the original Zachary's Karate Club graph \nand that of the partition with maximum modularity based on the greedy modularity optimization algorithm are equal.")

"""2. Use NetworkX to apply the Girvan–Newman algorithm and analyze the fi rst fi ve successive partitions produced by the Girvan–Newman algorithm. <br> For each partition, record the number of communities, community sizes, and modularity. Identify the partition with maximum modularity, check whether it aligns with the real-life split, and describe how modularity changes as edges are progressively removed. <hr>"""

import itertools # to iterate through community structures generated by the GN algorithm

n = 5 # five iterations of the GN algorithm
i = 1
track_max = 0
control_modularity_GN = 0
c = nx.community.girvan_newman(K)
for partitions in itertools.islice(c, n):
  print('The number of communities in iteration {} is {} communities.'.format(i, len(partitions)))
  partition_sizes = []
  for j in partitions:
    partition_sizes.append(len(j))
  print('The sizes of the communities in iteration {} are {}.'.format(i, partition_sizes)) # report sizes of the partitions
  print('The partition of nodes is given by \n{}.'.format(partitions)) # report the separation of nodes into different partitions
  print('\n')
  composition(partitions) # use the composition function to determine the composition of each partition in a community structure
  modularity = nx.community.modularity(K, communities = partitions)
  print('\nThe modularity of the graph after partition {} is {}.\n'.format(i, modularity)) # report modularity of the community structure
  print('-'*100)
  # determine community structure with the maximum modularity
  if modularity > control_modularity_GN:
    max_modularity_partitions_GN = partitions
    control_modularity_GN = modularity
    track_max = i
  i = i + 1

# report community structure with the maximum modularity

print('The partition with the maximum modularity = {} is partition {} with the communities \n{}.'.format(control_modularity_GN, track_max, max_modularity_partitions_GN))
print('\n')
composition(max_modularity_partitions_GN) # use the function composition to report composition of all partitions in a community structure
print('-'*100)

"""We compare the community structure with the maximum modularity with Zachary's Karate Club graph on the basis of number of communities and modularity. <hr>"""

if len(max_modularity_partitions_GN) != no_of_comm_real:
  print("The number of communities in the original Zachary's Karate Club graph \nand in the partition with maximum modularity based on the Girvan-Newman optimization algorithm are unequal.")
else:
  print("The number of communities in the original Zachary's Karate Club graph \nand in the partition with maximum modularity based on the Girvan-Newman optimization algorithm are equal.")

if control_modularity_GN != modularity_real:
  print("The modularity of the original Zachary's Karate Club graph \nand that of the partition with maximum modularity based on the Girvan-Newman optimization algorithm are unequal.")
else:
  print("The modularity of the original Zachary's Karate Club graph \nand that of the partition with maximum modularity based on the Girvan-Newman optimization algorithm are equal.")

"""5. The greedy modularity maximization algorithm is known to suff er from a "resolution limit." <br> Did you observe any instances where the algorithm merged small, distinct functional groups into a single community to artificially boost the modularity score?<hr>

We run the greedy modularity optimization algorithm by constraining the minimum number of communities using the ‘cutoff’ attribute, where it appears that the algorithm merges communities in an attempt to increase modularity. <br> <br>
Upon considering the attributes of the nodes being merged at each of the steps, we realize that the merger of nodes with larger communities not only helps increase modularity, but also classified nodes correctly into groups of nodes that have a preponderance of nodes with either of the two labels, Mr. Hi and Officer, from Zachary’s Karate Club graph. <hr>
"""

for i in range (2, 6): # 5 iterations
  c = nx.community.greedy_modularity_communities(K, cutoff = i,)
  modularity = nx.community.modularity(K, communities = c)
  print('The minimum number of communities allowed is {} communities.'.format(i)) # report minimum number of communities allowed
  print('The modularity of the graph in this case is {}.'.format(modularity)) # report modularity of the community structure
  print('\nThe communities are given as follows:') # report size of and nodes contained in each partition
  for j in range(len(c)):
    print('The size of community {} is {}.'.format(j+1, len(c[j])))
    c_nodes = [nodes for nodes in c[j]]
    print('The nodes in commmunity {} are {}.'.format(j+1, c_nodes))
  print('\n')
  composition(c) # use the composition function to report the composition of each partition in the community structure
  print('\n')
  print('-'*100)

"""Question 3:
---
Microbial association networks from two environments (i) Hospital and (ii) Metro stations are provided as edge lists with normalized correlation values as edge weights. Using Cytoscape, analyze each network individually and compare them. <hr>
1. Plot the degree distribution. <hr>
2. Plot the average clustering coefficient as a function of node degree. <hr>
3. Compute the average node degree, average clustering coeffi cient, and characteristic path length for each network and comment on the observed diff erences. <hr>
4. Identify associations unique to each environment as well as those common to both networks using Cytoscape. For the common interactions, examine how the normalized correlation values diff er between environments and visualize these changes using an appropriate plot. Finally, identify the top fi ve most interacting microbes in each environment from both the original networks and the unique interaction networks, and comment on your observations. <hr>

2. Plot the average clustering coefficient as a function of node degree. <hr>

Since Cytoscape does not readily provide methods to compute the average clustering coefficient, the Node Tables for both the graphs were imported in .csv format to a Python Notebook, where a script was written to calculate the average clustering coefficients of all nodes that have the same degree, and then obtain the desired plot for each of the two microbial association networks. <hr>
"""

df_hospital = pd.read_excel('q3-edges.xlsx', sheet_name = 'Hospital')
df_metro = pd.read_excel('q3-edges.xlsx', sheet_name = 'Metro')

df_hosp = pd.read_csv('Hospital_network.csv') # import relevant data
data_hospital = df_hosp[['Degree','ClusteringCoefficient']] # extract degree and clustering coefficient data

df_metro = pd.read_csv('Metro_network.csv') # import relevant data
data_metro = df_metro[['Degree','ClusteringCoefficient']] # extract degree and clustering coefficient data

def cc_vs_deg_plot(data):
  clusters = [[0]] # initialize a partition with the node 0
  # create groups of nodes that have the same degree
  for i in range(len(data)):
    check = False
    for j in clusters:
      if data.iloc[i,0] == j[0]:
        j.append(i)
        check = True
    if check == False:
     clusters.append([int(data.iloc[i,0]),i])
  degrees = [] # store all degrees observed in the network
  avg_cc = [] # store average clustering coefficient for all nodes with the same degree
  for list in clusters:
    if len(list) > 1:
      degrees.append(list[0])
      list.remove(list[0])
      sum_cc = 0
      for i in list:
        sum_cc = sum_cc + float(data.iloc[i,1]) # compute average clustering coefficient
      avg_cc.append(sum_cc/len(list))

  plt.scatter(degrees, avg_cc)
  plt.xlabel("Node Degree N(k)")
  plt.ylabel("Average clustering coefficient of nodes with degree k C(k)")
  plt.title('Average clustering coefficient as a function of node degree')
  plt.show()

  return

print('The average clustering coefficient versus node degree plot for the microbial association network in the Hospital environment is given as folows:')
cc_vs_deg_plot(data_hospital)

print('The average clustering coefficient versus node degree plot for the microbial association network in the Metro environment is given as folows:')
cc_vs_deg_plot(data_metro)

df_intersect = pd.read_csv('Intersection_Network.csv') # import data for nodes common to both environments
data_intersect = df_intersect[['name', 'Weights_diff']] # improt interaction names and difference between correlation values

fig, ax = plt.subplots(figsize=(10, 6))
seaborn.barplot(y='name', x='Weights_diff', data = data_intersect, color = 'blue') # use the seaborn package to plot the barplot
plt.xlabel('\nWeight_hospital - Weight_metro\n\nDifference between the correlation values between the Hospital and Metro environments.')
plt.ylabel('Microbial association interactions')
print('The differences between common microbial interactions in Hospital and Metro environments are given as follows:')

