# -*- coding: utf-8 -*-
"""BE23B007 - BT 5240 - Assignment 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TvQpRsfou8LEbPgItkrGnTOB26430VxI
"""

#import necessary packages
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
!pip install cobra --quiet

"""##Q1. FBA fundamentals:
---
While genome-scale models are often used to predict growth, cellular metabolism rarely operates with growth as its only objective. In many biological settings, carbon flux must be shared between biomass production and the synthesis or secretion of other metabolites. Changing this balance can alter pathway usage, reveal hidden bottlenecks, and expose vulnerabilities that are not obvious under standard growth optimisation. <br><hr>
1. Download the iJO1366 model (Escherichia coli) from BiGG Models and load it. Find the minimal media of the model and use it to simulate the following scenarios. Under both aerobic and anaerobic conditions, perform: <br>
i. flux balance analysis (FBA)<br>
ii. parsimonious fl ux balance analysis (pFBA) <br>
iii. flux variability analysis (FVA) <br>
From your analysis:<br>
a. Report the biomass obtained under aerobic and anaerobic conditions.<br>
b. Compare whether FBA and pFBA produce identical or different flux distributions.<br>
c. Identify the reactions that retain wide allowable fl ux ranges in FVA despite unchanged biomass.<br>
d. Briefly comment on the distinct insights provided by FBA, pFBA, and FVA, and the contexts in which each method is most useful.<br><hr>
2. The biomass-maximising solution does not necessarily favour metabolite secretion. Modify the model to promote ethanol production alongside biomass formation - construct a combined objective function using the original biomass reaction together with the ethanol secretion reaction (for example, by assigning different weights to each term). You may test any weighting scheme, but report results for at least two different weight combinations. Under both aerobic and anaerobic conditions:<br>
a. Describe your modified objective function and report the fi nal biomass and ethanol secretion flux.<br>
b. Compare how strongly biomass changes relative to the original growth-maximising solution and Identify reactions whose flux changes substantially when ethanol production is introduced.<br>
c. Briefly comment on how oxygen availability infl uences the balance between growth and ethanol production.<br><hr>
"""

import cobra
from cobra.io import read_sbml_model # to read an imported XML or SBML model

#load the iJO1366 model
!wget http://bigg.ucsd.edu/static/models/iJO1366.xml

"""1. Download the iJO1366 model (Escherichia coli) from BiGG Models and load it. Find the minimal media of the model and use it to simulate the following scenarios. Under both aerobic and anaerobic conditions, perform: <br>
i. flux balance analysis (FBA)<br>
ii. parsimonious fl ux balance analysis (pFBA) <br>
iii. flux variability analysis (FVA) <br>
From your analysis:<br>
a. Report the biomass obtained under aerobic and anaerobic conditions.<br>
b. Compare whether FBA and pFBA produce identical or different flux distributions.<br>
c. Identify the reactions that retain wide allowable fl ux ranges in FVA despite unchanged biomass.<br>
d. Briefl y comment on the distinct insights provided by FBA, pFBA, and FVA, and the contexts in which each method is most useful.<br><hr>
"""

#read the iJO1366 model
model_1 = read_sbml_model("iJO1366.xml")
print("The objective function of the iJO1366 model is given as follows:\n", model_1.objective)

#perform FBA and report the value of the objective function
fba_solution = model_1.optimize()
print("The status of the FBA solution is", fba_solution.status, ".")
print("The value of the objective function after performing FBA is", fba_solution.objective_value,'mmol_per_gDW_per_hr.')

#obtain the minimal medium for the given model
from cobra.medium import minimal_medium

min_medium = minimal_medium(model_1)

print("The minimal medium for the iJO1366 model is:\n")
print(min_medium)

"""The following simulations have been performed in the aerobic minimal medium:
<hr>
"""

#set up the minimal aerobic medium
model_aerobic = model_1.copy()
model_aerobic.medium = min_medium #set the medium as the minimal medium
print("The aerobic minimal medium is given as follows:\n")
model_aerobic.medium

# under aerobic conditions, perform FBA
fba_solution_min = model_aerobic.optimize()
print("The status of the FBA solution is", fba_solution_min.status, ".")
print("The value of the objective function after performing FBA is", fba_solution_min.objective_value,'mmol_per_gDW_per_hr.\n')

#under aerobic conditions, perform pFBA
from cobra.flux_analysis import pfba
pfba_solution_min = pfba(model_aerobic)
print("The status of the pFBA solution is", pfba_solution_min.status, ".")
print("The value of the biomass flux after performing pFBA is", pfba_solution_min.fluxes["BIOMASS_Ec_iJO1366_core_53p95M"],'mmol_per_gDW_per_hr.\n')

difference = fba_solution_min.fluxes - pfba_solution_min.fluxes # subtract the pFBA flux values from the FBA flux values
fluxes = pd.DataFrame({'FBA': fba_solution_min.fluxes, 'pFBA': pfba_solution_min.fluxes, 'Difference': difference})
print("The fluxes obtained after FBA, pFBA and the differences between the respective flux values, for some reactions, are as follows:\n")
fluxes.head()

#under aerobic conditions, perform FVA
from cobra.flux_analysis import flux_variability_analysis
fva_results_min = flux_variability_analysis(model=model_aerobic, reaction_list=model_1.reactions, fraction_of_optimum = 1.0) #the fraction of optimum FBA result allowed by FVA is kept equal to 1
print("The results of the flux variability analysis are as follows:\n")
fva_results_min

#report reactions such that the absolute difference between their flux values obtained in FBA and pFBA is greater than 0.01
diff_subst = []
for index, value in fluxes['Difference'].items():
  if abs(value) > 0.01:
    row = {'Reaction ID': index, 'FBA flux': fluxes.loc[index, 'FBA'], 'pFBA flux': fluxes.loc[index, 'pFBA'], 'Difference': value}
    diff_subst.append(row)
diff_subst_df = pd.DataFrame(diff_subst)
print("The absolute difference between the fluxes of the following", len(diff_subst_df), "reactions obtained in FBA and pFBA is greater than 0.01:\n")
diff_subst_df

#report reactions whose allowable flux ranges are >= 900 mmol/gDW/hr after performing FVA
fva_results_min['Difference'] = abs(fva_results_min['maximum'] - fva_results_min['minimum'])
fluxes_wide_range = []
for index, value in fva_results_min['Difference'].items():
  if value >= 900:
    row = {'Reaction ID': index, 'Absolute Value of Flux Range after FVA': value}
    fluxes_wide_range.append(row)
fluxes_wide_range_df = pd.DataFrame(fluxes_wide_range)
print("The", len(fluxes_wide_range_df), "reactions whose allowable flux ranges are >= 900 mmol/gDW/hr after performing FVA are as follows:\n")
fluxes_wide_range_df

"""The following simulations have been performed in the anaerobic minimal medium:<hr>"""

#set up anaerobic conditions
model_anaerobic = model_1.copy()

medium_anaerobic = model_anaerobic.medium
medium_anaerobic["EX_o2_e"] = 0
model_anaerobic.medium = medium_anaerobic

model_anaerobic.medium = minimal_medium(model_anaerobic)


print("The anaerobic minimal medium is given as follows:\n")
model_anaerobic.medium

#under anaerobic conditions, perform FBA

fba_solution_min_anaerobe = model_anaerobic.optimize()
print("The status of the FBA solution is", fba_solution_min_anaerobe.status, ".")
print("The value of the objective function after performing FBA is", fba_solution_min_anaerobe.objective_value,'mmol_per_gDW_per_hr.\n')

#under anaerobic conditions, perform pFBA
pfba_solution_min_anaerobe = pfba(model_anaerobic)
print("The status of the pFBA solution is", pfba_solution_min_anaerobe.status)
print("The value of the biomass flux after performing pFBA is", pfba_solution_min_anaerobe.fluxes["BIOMASS_Ec_iJO1366_core_53p95M"],'mmol_per_gDW_per_hr.\n')

difference_anaerobe = fba_solution_min_anaerobe.fluxes - pfba_solution_min_anaerobe.fluxes # subtract the pFBA flux values from the FBA flux values
fluxes_anaerobe = pd.DataFrame({'FBA': fba_solution_min_anaerobe.fluxes, 'pFBA': pfba_solution_min_anaerobe.fluxes, 'Difference': difference_anaerobe})
print("The fluxes obtained after FBA, pFBA and the differences between the respective flux values, for some reactions, are as follows:\n")
fluxes_anaerobe

#under anaerobic conditions, perform FVA
fva_results_min_anaerobe = flux_variability_analysis(model=model_anaerobic, reaction_list=model_1.reactions, fraction_of_optimum = 1.0)
print("The results of the flux variability analysis are as follows:\n")
fva_results_min_anaerobe

#report reactions such that the absolute difference between their flux values obtained in FBA and pFBA is greater than 0.01
diff_subst_anaerobe = []
for index, value in fluxes_anaerobe['Difference'].items():
  if abs(value) > 0.01:
    row = {'Reaction ID': index, 'FBA flux': fluxes_anaerobe.loc[index, 'FBA'], 'pFBA flux': fluxes_anaerobe.loc[index, 'pFBA'], 'Difference': value}
    diff_subst_anaerobe.append(row)
diff_subst_anaerobe_df = pd.DataFrame(diff_subst_anaerobe)
print("The absolute difference between the fluxes of the following", len(diff_subst_anaerobe_df), "reactions obtained in FBA and pFBA is greater than 0.01:\n")
diff_subst_anaerobe_df

#report reactions whose allowable flux ranges are >= 900 mmol/gDW/hr after performing FVA
fva_results_min_anaerobe['Difference'] = abs(fva_results_min_anaerobe['maximum'] - fva_results_min_anaerobe['minimum'])
fluxes_wide_range_anaerobe = []
for index, value in fva_results_min_anaerobe['Difference'].items():
  if value >= 900:
    row = {'Reaction ID': index, 'Absolute Value of Flux Range after FVA': value}
    fluxes_wide_range_anaerobe.append(row)
fluxes_wide_range_anaerobe_df = pd.DataFrame(fluxes_wide_range_anaerobe)
print("The", len(fluxes_wide_range_anaerobe_df), "reactions whose allowable flux ranges are >= 900 mmol/gDW/hr after performing FVA are as follows:\n")
fluxes_wide_range_anaerobe_df

"""2. The biomass-maximising solution does not necessarily favour metabolite secretion. Modify the model to promote ethanol production alongside biomass formation - construct a combined objective function using the original biomass reaction together with the ethanol secretion reaction (for example, by assigning different weights to each term). You may test any weighting scheme, but report results for at least two different weight combinations. Under both aerobic and anaerobic conditions:<br>
a. Describe your modified objective function and report the fi nal biomass and ethanol secretion flux.<br>
b. Compare how strongly biomass changes relative to the original growth-maximising solution and Identify reactions whose flux changes substantially when ethanol production is introduced.<br>
c. Briefly comment on how oxygen availability influences the balance between growth and ethanol production.<br><hr>

The following simulations have been performed in aerobic media:<hr>
"""

#we iterate through different weights for the ethanol exchange reaction, and report only those weights for which the biomass reaction had a non-zero flux
model_etoh_aerobic = model_1.copy()

reaction_etoh = model_etoh_aerobic.reactions.get_by_id("EX_etoh_e")
reaction_biomass = model_etoh_aerobic.reactions.get_by_id("BIOMASS_Ec_iJO1366_core_53p95M")

wt = [i/100 for i in range(0, 100)] #iterate through different weights for the ethanol exchange reaction
data_list_aero = []
biomass_fluxes = []
ethanol_wt = []

for wt in wt:
  model_etoh_aerobic.objective = reaction_etoh.flux_expression * wt + reaction_biomass.flux_expression * (1-wt) #set up the objective reaction by assigning weights to the biomass and ethanol exchange reactions

  fba_solution_etoh_aerobic = model_etoh_aerobic.optimize()

  biomass_fluxes.append(fba_solution_etoh_aerobic.fluxes.loc["BIOMASS_Ec_iJO1366_core_53p95M"])
  ethanol_wt.append(wt)

  # we report the weights for whom the biomass reaction had a non-zero value, that is, the objective function was biologically feasible
  if fba_solution_etoh_aerobic.fluxes.loc["BIOMASS_Ec_iJO1366_core_53p95M"] > 0:
    row = {'Weight of EtOH secretion reaction': wt, 'Weight of Biomass reaction': (1-wt), 'EtOH reaction flux': fba_solution_etoh_aerobic.fluxes.loc["EX_etoh_e"], 'Biomass flux': fba_solution_etoh_aerobic.fluxes.loc["BIOMASS_Ec_iJO1366_core_53p95M"]}
    data_list_aero.append(row)
data_list_aero_df = pd.DataFrame(data_list_aero)
print("The different weights of the ethanol exchange reaction for which a non-zero biomass flux was obtained are as follows:\n")
data_list_aero_df

#consider one of the weights from the above DataFrame for the following analysis, here weight = 0.05
#wt = 0.04
wt = 0.05
model_etoh_aerobic_simulate = model_1.copy()

reaction_etoh_simulate = model_etoh_aerobic_simulate.reactions.get_by_id("EX_etoh_e")
reaction_biomass_simulate = model_etoh_aerobic_simulate.reactions.get_by_id("BIOMASS_Ec_iJO1366_core_53p95M")

model_etoh_aerobic_simulate.objective = reaction_etoh_simulate.flux_expression * wt + reaction_biomass_simulate.flux_expression * (1-wt)
fba_solution_etoh_aerobic_simulate = model_etoh_aerobic_simulate.optimize()

print("The flux through the ethanol secretion reaction is",fba_solution_etoh_aerobic_simulate.fluxes.loc["EX_etoh_e"],
    "mmol_per_gDW_per_hr \nand the flux through the biomass reaction is", fba_solution_etoh_aerobic_simulate.fluxes.loc["BIOMASS_Ec_iJO1366_core_53p95M"], "mmol_per_gDW_per_hr.")

#report the difference between the flux values for the different reactions obtained by performing the normal FBA and by including the ethanol exchange reaction in the objective function

data_list_aero_1 = []

for rxn in model_etoh_aerobic_simulate.reactions:
  diff = fba_solution_etoh_aerobic_simulate.fluxes.loc[rxn.id] - fba_solution.fluxes.loc[rxn.id]

  if abs(diff) >= 5:  #report only when the difference between the flux values is greater than 1
    row = {'Reaction ID': rxn.id, 'Simulated Flux': fba_solution_etoh_aerobic_simulate.fluxes.loc[rxn.id], 'FBA flux': fba_solution.fluxes.loc[rxn.id], 'Difference': diff }
    data_list_aero_1.append(row)

data_list_aero_1_df = pd.DataFrame(data_list_aero_1)
print("The absolute differences (with magnitude >=5) between the flux values of the following", len(data_list_aero_1_df),"reactions obtained by performing FBA\nand by including the ethanol exchange reaction in the objective function with weight=", wt, "are as follows:\n")
data_list_aero_1_df

#plot the variation of biomass flux with the weight of the ethanol exchange reaction, in aerobic conditions
plt.plot(ethanol_wt, biomass_fluxes)
plt.xlabel("Weight of the Ethanol Exchange Reaction")
plt.ylabel("Biomass Flux")
plt.title("Variation of biomass flux with weight given to the Ethanol Exchange Reaction")
plt.grid()
plt.show()

"""The following simulations have been performed under anaerobic conditions:<hr>"""

#we iterate through different weights for the ethanol exchange reaction, and report only those weights for which the biomass reaction had a non-zero flux
model_etoh_anaerobic = model_1.copy()

model_etoh_anaerobic.reactions.get_by_id("EX_o2_e").lower_bound = 0
model_etoh_anaerobic.reactions.get_by_id("EX_o2_e").upper_bound = 0

reaction_etoh = model_etoh_anaerobic.reactions.get_by_id("EX_etoh_e")
reaction_biomass = model_etoh_anaerobic.reactions.get_by_id("BIOMASS_Ec_iJO1366_core_53p95M")
wt = [i/100 for i in range(0, 100)]
data_list_anaero = []
biomass_fluxes_anaerobe = []
for wt in wt:
  model_etoh_anaerobic.objective = reaction_etoh.flux_expression * wt + reaction_biomass.flux_expression * (1-wt)
  fba_solution_etoh_anaerobic = model_etoh_anaerobic.optimize()
  biomass_fluxes_anaerobe.append(fba_solution_etoh_anaerobic.fluxes.loc["BIOMASS_Ec_iJO1366_core_53p95M"])

  if fba_solution_etoh_anaerobic.fluxes.loc["BIOMASS_Ec_iJO1366_core_53p95M"] > 0:
    row = {'Weight of EtOH secretion reaction': wt, 'Weight of Biomass reaction': (1-wt), 'EtOH reaction flux': fba_solution_etoh_anaerobic.fluxes.loc["EX_etoh_e"], 'Biomass flux': fba_solution_etoh_anaerobic.fluxes.loc["BIOMASS_Ec_iJO1366_core_53p95M"]}
    data_list_anaero.append(row)

print("The different weights of the ethanol exchange reaction for which a non-zero biomass flux was obtained are as follows:\n")
data_list_anaero_df = pd.DataFrame(data_list_anaero)
data_list_anaero_df

#consider one of the weights from the above DataFrame for the following analysis, here weight = 0.04
model_etoh_anaerobic_simulate = model_1.copy()

model_etoh_anaerobic_simulate.reactions.get_by_id("EX_o2_e").lower_bound = 0
model_etoh_anaerobic_simulate.reactions.get_by_id("EX_o2_e").upper_bound = 0

reaction_etoh_simulate = model_etoh_anaerobic_simulate.reactions.get_by_id("EX_etoh_e")
reaction_biomass_simulate = model_etoh_anaerobic_simulate.reactions.get_by_id("BIOMASS_Ec_iJO1366_core_53p95M")
#wt = 0.04
wt = 0.05

model_etoh_anaerobic_simulate.objective = reaction_etoh_simulate.flux_expression * wt + reaction_biomass_simulate.flux_expression * (1-wt)
fba_solution_etoh_anaerobic_simulate = model_etoh_anaerobic_simulate.optimize()

print("The flux through the ethanol secretion reaction is",fba_solution_etoh_anaerobic_simulate.fluxes.loc["EX_etoh_e"],
    "mmol_per_gDW_per_hr \nand the flux through the biomass reaction is", fba_solution_etoh_anaerobic_simulate.fluxes.loc["BIOMASS_Ec_iJO1366_core_53p95M"], "mmol_per_gDW_per_hr.")

#report the difference between the flux values for the different reactions obtained by performing the normal FBA and by including the ethanol exchange reaction in the objective function

data_list_anaero_1 = []

for rxn in model_etoh_anaerobic_simulate.reactions:
  diff = fba_solution_etoh_anaerobic_simulate.fluxes.loc[rxn.id] - fba_solution.fluxes.loc[rxn.id]

  if abs(diff) >= 5: #report only when the difference between the flux values is greater than 1
    row = {'Reaction ID': rxn.id, 'Simulated Flux': fba_solution_etoh_anaerobic_simulate.fluxes.loc[rxn.id], 'FBA flux': fba_solution.fluxes.loc[rxn.id], 'Difference': diff }
    data_list_anaero_1.append(row)

print("The absolute differences (with magnitude >=5) between the flux values of the following", len(data_list_anaero_1), "reactions obtained by performing FBA\nand by including the ethanol exchange reaction in the objective function with weight=", wt, "are as follows:\n")

data_list_anaero_1_df = pd.DataFrame(data_list_anaero_1)
data_list_anaero_1_df

#plot the variation of biomass flux with the weight of the ethanol exchange reaction in anaerobic conditions
plt.plot(ethanol_wt, biomass_fluxes_anaerobe)
plt.xlabel("Weight of the Ethanol Exchange Reaction")
plt.ylabel("Biomass Flux")
plt.title("Variation of biomass flux with weight given to the Ethanol Exchange Reaction")
plt.grid()
plt.show()

"""c. Briefly comment on how oxygen availability influences the balance between growth and ethanol production. <hr>"""

#plot the variation of biomass flux with oxygen availability (upper bound of the oxygen exchange reaction)
fba_sols_o2 = []
o2_upper_bounds = []
o2_medium = model_1.medium["EX_o2_e"]
ethanol_fluxes = []
for i in range(0,101):
  model_o2_sim = model_1.copy()
  #wt = 0.01
  wt = 0.05

  reaction_etoh_simulate = model_o2_sim.reactions.get_by_id("EX_etoh_e")
  reaction_biomass_simulate = model_o2_sim.reactions.get_by_id("BIOMASS_Ec_iJO1366_core_53p95M")
  model_o2_sim.objective = reaction_etoh_simulate.flux_expression * wt + reaction_biomass_simulate.flux_expression * (1-wt)

  fraction = o2_medium * i / 100
  model_o2_sim.reactions.get_by_id("EX_o2_e").upper_bound = fraction
  o2_upper_bounds.append(fraction)

  fba_solution_o2_sim = model_o2_sim.optimize()
  fba_sols_o2.append(fba_solution_o2_sim.objective_value)
  ethanol_fluxes.append(fba_solution_o2_sim.fluxes["EX_etoh_e"])

plt.plot(o2_upper_bounds, fba_sols_o2)
plt.xlabel("Upper Bound of the Oxygen Exchange Reaction")
plt.ylabel("Biomass Flux")
plt.title("Variation of Biomass Flux with Oxygen Availability")
plt.grid()
plt.show()

#plot the variation of biomass flux with oxygen availability (upper bound of the oxygen exchange reaction)
plt.plot(o2_upper_bounds, ethanol_fluxes)
plt.xlabel("Upper Bound of the Oxygen Exchange Reaction")
plt.ylabel("Ethanol Flux")
plt.title("Variation of Ethanol Flux with Oxygen Availability")
plt.grid()
plt.show()

"""##Q2. Cross-pathogen target discovery:
<hr>
Bacterial pathogens continue to remain a major challenge because of their ability to adapt quickly to changing environments and therapeutic interventions. Some survive for long periods inside host tissues under highly restricted conditions, while others thrive in clinical settings by exploiting metabolic fl exibility and resistance mechanisms. Despite these differences, every pathogen faces the same basic requirement: it must use whatever nutrients are available to sustain growth, maintain cellular functions, and reproduce. Studying metabolism at the network level allows us to ask whether very different
organisms rely on common biochemical strategies, and whether these shared requirements can reveal useful intervention points. <br>
Mycobacterium tuberculosis is a slow-growing pathogen adapted to long-term survival within the host, often under nutrient and oxygen-limited conditions. In contrast, Acinetobacter baumannii is an opportunistic hospital-associated pathogen known for rapid adaptation and multidrug resistance. Their lifestyles are clearly different, but both must maintain their core metabolic processes that support growth.<hr>
1. Download the models iNJ661 (Mycobacterium tuberculosis) and iCN718 (Acinetobacter baumannii) from BiGG Models (use a format compatible with your system; ‘.xml’ is recommended). Compare the two models in terms of genes, metabolites, and reactions, and examine whether differences in gene content are refl ected proportionally in overall network size. In particular:<br>
a. Does a higher number of genes correspond to a higher number of reactions and metabolites? Which organism shows a larger reaction-to-gene ratio?<br>
b. Briefl y comment on how the lifestyle of each organism may explain the differences or similarities you observe.
<hr>
2. Identify essential genes in both models by testing the effect of individual gene deletions on growth. From your results:<br>
a. List the essential genes identifi ed in each organism.<br>
b. Identify the essential genes common to both models (with matching gene annotations). Examine whether these shared genes are associated with central metabolism, biosynthetic pathways, transport functions, or other cellular processes.
<hr>
3. The genes found to be essential in both organisms represent potential common targets for metabolic intervention. Choose one shared essential gene and examine it in more detail:<br>
a. Identify the metabolic function associated with the gene and briefl y mention why disrupting this function is expected to strongly affect growth in both organisms.<br>
b. Briefly examine available literature to see whether inhibition of this gene, or the pathway it belongs to, has been associated with reduced growth or loss of viability in either organism or in related bacterial species.
<hr>
"""

!wget http://bigg.ucsd.edu/static/models/iNJ661.xml #import the Mtb model

!wget http://bigg.ucsd.edu/static/models/iCN718.xml #import the Acinetobacter model

#load the required models
model_mtb = read_sbml_model("iNJ661.xml") #the Mycobacterium tuberculosis model
model_acbac = read_sbml_model("iCN718.xml") #the Acinetobacter baumanii model

#report the number of genes, metabolites and reactions, and the reaction-to-gene ratio for each model
mtb_genes = len(model_mtb.genes)
mtb_metabolites = len(model_mtb.metabolites)
mtb_reactions = len(model_mtb.reactions)

acbac_genes = len(model_acbac.genes)
acbac_metabolites = len(model_acbac.metabolites)
acbac_reactions = len(model_acbac.reactions)

print("The number of genes in the Mycobacterium tuberculosis model is", mtb_genes,".")
print("The number of metabolites in the Mycobacterium tuberculosis model is", mtb_metabolites,".")
print("The number of reactions in the Mycobacterium tuberculosis model is", mtb_reactions,".")
print("The reaction-to-gene ratio for the Mycobacterium tuberculosis model is", mtb_reactions/mtb_genes,".\n")


print("The number of genes in the Acinetobacter baumannii model is", acbac_genes,".")
print("The number of metabolites in the Acinetobacter baumannii model is", acbac_metabolites,".")
print("The number of reactions in the Acinetobacter baumannii model is", acbac_reactions,".")
print("The reaction-to-gene ratio for the Acinetobacter baumannii model is", acbac_reactions/acbac_genes,".")

import cobra.flux_analysis

#report the essential genes and the reactions catalysed by the enzymes encoded by them in the M. tuberculosis model
essential_genes_mtb = cobra.flux_analysis.find_essential_genes(model_mtb)
list_genes_mtb = []
for gene in essential_genes_mtb:
  rxns = ""
  for rxn in gene.reactions:
    rxns = rxns + rxn.id + ","
  rxns = rxns.removesuffix(",")
  row = {'gene_ID': gene.id, 'gene_reaction': rxns}
  list_genes_mtb.append(row)
list_genes_mtb_df = pd.DataFrame(list_genes_mtb)
print("The essential genes in the Mycobacterium tuberculosis model are given as follows:")
list_genes_mtb_df

#report the essential genes and the reactions catalysed by the enzymes encoded by them in the A. baumannii model
essential_genes_acbac = cobra.flux_analysis.find_essential_genes(model_acbac)
list_genes_acbac = []
for gene in essential_genes_acbac:
  rxns = ""
  for rxn in gene.reactions:
    rxns = rxns + rxn.id + ","
  rxns = rxns.removesuffix(",")
  row = {'gene_ID': gene.id, 'gene_reaction': rxns}
  list_genes_acbac.append(row)
list_genes_acbac_df = pd.DataFrame(list_genes_acbac)
print("The essential genes in the Acinetobacter baumannii model are given as follows:")
list_genes_acbac_df

#report the common essential genes and the reactions catalysed by the enzymes encoded by them in the two models
df_merged = pd.merge(list_genes_acbac_df, list_genes_mtb_df, on = 'gene_reaction')
rxn_names = []
for rxns in df_merged['gene_reaction']:
  rxn_list = rxns.split(",")
  for rxn in rxn_list:
    GPR = model_mtb.reactions.get_by_id(rxn).gene_reaction_rule
    gene_names = GPR.split(",")
    genes = ", ".join([model_mtb.genes.get_by_id(i).name for i in gene_names])
    row = {"Gene": genes, "Reaction": model_mtb.reactions.get_by_id(rxn).name}
    rxn_names.append(row)
df_essential_genes = pd.DataFrame(rxn_names)
print("The", len(df_essential_genes),"essential genes common to both the Mycobacterium tuberculosis and Acinetobacter baumanii models are:\n")
df_essential_genes

df_essential_genes.to_csv("essential_genes.csv")
print("The list of common essential genes was downloaded successfully.")

"""For example:"""

model_acbac.genes.get_by_id("ABAYE_RS08660")

model_mtb.genes.get_by_id("Rv1699")

"""Q3. Synthetic lethality across diets:<hr>

Metabolic networks often contain hidden redundancies that are not apparent under single gene deletions. In many cases, loss of a single gene can be compensated for by an alternative pathway, while simultaneous disruption of two genes removes this backup capacity and abolishes growth.<hr>
1. Download the Escherichia coli core model from BiGG Models, load it and perform basic validation checks expected for a genome-scale metabolic model before beginning any simulations. As part of model validation:<br>
a. Report the number of genes, metabolites, and reactions before and after validation.<br>
b. Describe the checks performed and any corrections made to the model.<br>
c. Employ the algorithm taught in class to identify the gene knockout targets - (single genes, pairs and triplets) that would enhance the production of ethanol.<hr>
2. Identify synthetic lethal gene pairs by implementing the FAST-SL algorithm(use the fastsl python package).
Perform the analysis under the following growth conditions:<br>
i. Glucose as the sole carbon source (10 mmol·gDW⁻¹·h⁻¹)<br>
ii. Acetate as the sole carbon source (10 mmol·gDW⁻¹·h⁻¹)<br>
iii. In a medium comprising only the components absolutely necessary for growth
From your results:<br>
a. List the synthetic lethal gene pairs identified under each condition.<br>
b. Identify gene pairs common to all three media, as well as those specifi c to individual conditions.<br>
c. Briefly comment on whether synthetic lethality depends on the media condition, i.e., the nutrient environment.<hr>
3. Select one synthetic lethal gene pair and explain:<br>
a. Why does the deletion of either of the genes still allow growth and why does the simultaneous deletion inhibit biomass production?<br>
b. Which redundant metabolic route or alternative pathway is disrupted in the double deletion?<hr>
"""

!pip install fastsl --quiet #install the fastsl package
!pip install swiglpk --quiet #install the GLPK solver

!sed -i 's/solver_tol = model.solver.configuration.tolerances.optimality/solver_tol = 1e-9/' \
/usr/local/lib/python3.12/dist-packages/fastsl/genes.py

"""1. Download the Escherichia coli core model from BiGG Models, load it and perform basic validation checks expected for a genome-scale metabolic model before beginning any simulations. As part of model validation:<br>

"""

!wget http://bigg.ucsd.edu/static/models/e_coli_core.json #load the E. coli core model

#read the E. coli core model
from cobra.io import load_json_model, write_sbml_model

model_ecoli_core = load_json_model("e_coli_core.json")
write_sbml_model(model_ecoli_core, "e_coli_core.xml")

"""a. Report the number of genes, metabolites, and reactions before and after validation.<hr>"""

print("Total number of genes in the E. coli core model is", len(model_ecoli_core.genes), ".")
print("Total number of reactions in the E. coli core model is", len(model_ecoli_core.reactions), ".")
print("Total number of metabolites in the E. coli core model is", len(model_ecoli_core.metabolites), ".")

"""b. Describe the checks performed and any corrections made to the model.<hr>"""

cobra.io.sbml.validate_sbml_model("e_coli_core.xml")

cobra.manipulation.validate.check_mass_balance(model_ecoli_core)

cobra.flux_analysis.variability.find_blocked_reactions(model_ecoli_core)

"""c. Employ the algorithm taught in class to identify the gene knockout targets - (single genes, pairs and triplets) that would enhance the production of ethanol.<hr>"""

!pip install cameo --quiet

import cameo
import collections
import collections.abc

collections.Mapping = collections.abc.Mapping
collections.MutableMapping = collections.abc.MutableMapping
collections.Sequence = collections.abc.Sequence


from cameo import load_model
from cameo.strain_design.deterministic.linear_programming import OptKnock

print(model_ecoli_core.objective)

#perform OptKnock for single gene deletions
model = model_ecoli_core.copy()
#model.medium = minimal_medium(model)

optknock = OptKnock(model)
biomass = model.reactions.get_by_id("BIOMASS_Ecoli_core_w_GAM")
target = model.reactions.get_by_id("EX_etoh_e") #the target reaction, here, is set as the ethanol exchange reaction

result_1 = optknock.run(target=target, biomass = biomass, max_knockouts=1, knock_out="genes")

design_1 = pd.DataFrame(result_1.data_frame)
design_1

#perform OptKnock for double gene deletions
result_2 = optknock.run(target=target, biomass = biomass, max_knockouts = 2, knock_out="genes")

design_2 = pd.DataFrame(result_2.data_frame)

design_2

#perform OptKnock for triple gene deletions
result_3 = optknock.run(target=target, biomass = biomass, max_knockouts = 3, knock_out="genes")

design_3 = pd.DataFrame(result_3.data_frame)

design_3

"""2. Identify synthetic lethal gene pairs by implementing the FAST-SL algorithm(use the fastsl python package).<hr>

Perform the analysis under the following growth conditions:<br>
i. Glucose as the sole carbon source (10 mmol·gDW⁻¹·h⁻¹)<br>
ii. Acetate as the sole carbon source (10 mmol·gDW⁻¹·h⁻¹)<br>
iii. In a medium comprising only the components absolutely necessary for growth
From your results:<br>
"""

#set the glucose exchange flux to -10 mmol/gDW-hr (uptake by the cell)
model_ecoli_core.reactions.get_by_id("EX_glc__D_e").upper_bound = -10
model_ecoli_core.reactions.get_by_id("EX_glc__D_e").lower_bound = -10

model_ecoli_core.medium

#perform FastSL to identify SL pairs of genes
!fast-sl e_coli_core.xml --genes

path = "/content/fast-sl-results/e_coli_core/genes/e_coli_core_double_lethal_genes.csv"
#report the SL pairs of genes in this case
data_sl_glc = pd.read_csv(path, header=None)
print("The number of synthetic lethal genes identified when glucose was kept as the sole carbon source is", len(data_sl_glc),".")
data_sl_glc.head(10)

#for a given gene, report the reactions catalysed by the enzyme encoded by it
def get_gene_reactions(model, gene_id):
  try:
      gene = model.genes.get_by_id(gene_id)
      return [rxn.id for rxn in gene.reactions]
  except:
      return []

#report the reactions catalysed by the enzymes encoded by the SL pairs of genes identified above
data_rxn_sl_glc = []
for i, row in data_sl_glc.iterrows():

    gene_1 = row[0]
    gene_2 = row[1]

    rxn_1 = get_gene_reactions(model_ecoli_core, gene_1)
    rxn_2 = get_gene_reactions(model_ecoli_core, gene_2)

    row = {'Gene 1': gene_1, 'Reaction(s) 1': rxn_1, 'Gene 2': gene_2, 'Reaction(s) 2': rxn_2}
    data_rxn_sl_glc.append(row)
df_rxn_sl_glc = pd.DataFrame(data_rxn_sl_glc)
print("The reactions catalysed by the enzymes encoded by the synthetic lethal pairs of genes \nwhen glucose was kept as the sole carbon source are as follows:")
df_rxn_sl_glc.head(10)

#fix the acetate exchange flux to -10 mmol/gDW-hr and the glucode exchange flux to 0 mmol/gDW-hr
model_ecoli_core.reactions.get_by_id("EX_glc__D_e").upper_bound = 0
model_ecoli_core.reactions.get_by_id("EX_glc__D_e").lower_bound = 0

model_ecoli_core.reactions.get_by_id("EX_ac_e").lower_bound = -10
model_ecoli_core.reactions.get_by_id("EX_ac_e").upper_bound = -10

model_ecoli_core.medium

write_sbml_model(model_ecoli_core, "e_coli_core_ac.xml")

#perform FastSL to identify SL pairs of genes
!fast-sl e_coli_core_ac.xml --genes

path_ac = "/content/fast-sl-results/e_coli_core/genes/e_coli_core_double_lethal_genes.csv"

#report the SL pairs of genes identified above
data_sl_ac = pd.read_csv(path_ac, header=None)
print("The number of synthetic lethal genes identified when acetate was kept as the sole carbon source is", len(data_sl_ac),".")
data_sl_ac.head()

data_sl_ac.head(10)

#report the reactions catalysed by the enzymes encoded by the SL pairs of genes identified above
data_rxn_sl_ac = []
for i, row in data_sl_ac.iterrows():

    gene_1 = row[0]
    gene_2 = row[1]

    rxn_1 = get_gene_reactions(model_ecoli_core, gene_1)
    rxn_2 = get_gene_reactions(model_ecoli_core, gene_2)

    row = {'Gene 1': gene_1, 'Reaction(s) 1': rxn_1, 'Gene 2': gene_2, 'Reaction(s) 2': rxn_2}
    data_rxn_sl_ac.append(row)
df_rxn_sl_ac = pd.DataFrame(data_rxn_sl_ac)
print("The reactions catalysed by the enzymes encoded by the synthetic lethal pairs of genes \nwhen acetate was kept as the sole carbon source are as follows:")
df_rxn_sl_ac.head(10)

len(df_rxn_sl_ac)

#reset the flux bounds for the glucose and acetate exchange reactions
model_ecoli_core.reactions.get_by_id("EX_glc__D_e").lower_bound = -10
model_ecoli_core.reactions.get_by_id("EX_glc__D_e").upper_bound = 10

model_ecoli_core.reactions.get_by_id("EX_ac_e").upper_bound = 0
model_ecoli_core.reactions.get_by_id("EX_ac_e").lower_bound = 0

model_ecoli_core.medium

#obtain the minimal medium comprising glucose as the sole carbon source
min_medium_glc = cobra.medium.minimal_medium(model_ecoli_core)
min_medium_glc

#set the model medium as the minimal medium obtained above
model_ecoli_core.medium = min_medium_glc

model_ecoli_core.medium

write_sbml_model(model_ecoli_core, "e_coli_core_min_glc.xml")

#perform FastSL to identify SL pairs of genes
!fast-sl e_coli_core_min_glc.xml --genes

path_min_glc = "/content/fast-sl-results/e_coli_core/genes/e_coli_core_double_lethal_genes.csv"
#report the SL pairs of genes identified above
data_sl_min_glc = pd.read_csv(path, header=None)
print("The number of synthetic lethal genes identified when glucose was kept as the sole carbon source in minimal media is", len(data_sl_min_glc),".")
data_sl_min_glc

data_sl_min_glc.head(10)

#report the reactions catalysed by the enzymes encoded by the SL pairs of genes identified above
data_rxn_sl_min_glc = []
for i, row in data_sl_min_glc.iterrows():

    gene_1 = row[0]
    gene_2 = row[1]

    rxn_1 = get_gene_reactions(model_ecoli_core, gene_1)
    rxn_2 = get_gene_reactions(model_ecoli_core, gene_2)

    row = {'Gene 1': gene_1, 'Reaction(s) 1': rxn_1, 'Gene 2': gene_2, 'Reaction(s) 2': rxn_2}
    data_rxn_sl_min_glc.append(row)
df_rxn_sl_min_glc = pd.DataFrame(data_rxn_sl_min_glc)
print("The reactions catalysed by the enzymes encoded by the synthetic lethal pairs of genes \nwhen glucose was kept as the sole carbon source in minimal media are as follows:")
df_rxn_sl_min_glc

df_rxn_sl_min_glc.head(10)

"""b. Identify gene pairs common to all three media, as well as those specific to individual conditions.<hr>"""

#identify the pairs of SL genes common to all three media
common_rows_non_minimal = pd.merge(df_rxn_sl_glc, df_rxn_sl_ac, on=['Gene 1','Gene 2'], how='inner')
print("The following pairs of synthetic lethal genes are common across the following two cases:\n1. When Glucose is used as the sole carbon source\n2. When Acetate is used as the sole carbon source\n")
common_rows_non_minimal.iloc[:, 0:4]

common_rows_all = pd.merge(common_rows_non_minimal, df_rxn_sl_min_glc, on=['Gene 1','Gene 2'], how='inner')
print("The following pairs of synthetic lethal genes were common across all three cases:\n1. When Glucose is used as the sole carbon source\n2. When Acetate is used as the sole carbon source\n3. When Glucose is used as the sole carbon source in minimal media\n")
common_rows_all.iloc[:, 0:4]

"""The following pair of synthetic lethal genes was used for sub-question 3. <hr>"""

model_ecoli_core.genes.get_by_id("b1761")

model_ecoli_core.genes.get_by_id("b3212")

#identify the pairs of SL genes unique to a certain medium
def find_unique(data1, data2, data3):
  data_unique = data1
  data_unique = [x for x in data1 if x not in data2]
  data_unique = [x for x in data_unique if x not in data3]
  df_data1_unique = pd.DataFrame(data_unique)
  return df_data1_unique

data1 = data_rxn_sl_glc
data2 = data_rxn_sl_ac
data3 = data_rxn_sl_min_glc

#identify the pairs of SL genes unique to the medium with glucose as the sole carbon source
df_data1_unique = find_unique(data1, data2, data3)
print(len(df_data1_unique),"pairs of synthetic lethals are unique to the case where Glucose was kept as the sole carbon source:")
df_data1_unique

df_data1_unique.head(10)

#identify the pairs of SL genes unique to the medium with acetate as the sole carbon source
df_data2_unique = find_unique(data2, data1, data3)
print(len(df_data2_unique),"pairs of synthetic lethals are unique to the case where Acetate was kept as the sole carbon source:")
df_data2_unique

#identify the pairs of SL genes unique to the minimal medium with glucose as the sole carbon source
df_data3_unique = find_unique(data3, data1, data2)
print(len(df_data3_unique),"pairs of synthetic lethals are unique to the case where Glucose was kept as the sole carbon source in the minimal media:")
df_data3_unique

